name: Setup project
description: Setup project with node docker-buildx
inputs:
  node-version:
    description: Node.js version
    default: lts/*
    required: false
  node-registry-url:
    description: Node.js registry URL
    default: https://registry.npmjs.org
    required: false
  package-manager:
    description: Package manager to use
    required: false
    default: yarn
  package-manager-install-command:
    description: Package manager install command
    required: false
    default: install
  package-manager-install-args:
    description: Package manager install arguments
    required: false
    default: --frozen-lockfile
  dependencies:
    description: Install dependencies
    required: false
  install-buildx:
    description: Install docker buildx
    required: false
  install-playwright:
    description: Install playwright
    required: false
  playwright-browsers:
    description: Playwright browsers
    required: false
    default: chromium webkit firefox
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        registry-url: ${{ inputs.node-registry-url }}
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.package-manager }}

    - name: Install npm dependencies
      if: ${{ inputs.dependencies == 'true' }}
      shell: bash
      run: ${{ inputs.package-manager }} ${{ inputs.package-manager-install-command }} ${{ inputs.package-manager-install-args }}

    - name: Install docker buildx
      if: ${{ inputs.install-buildx == 'true' }}
      uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3

    - name: Install playwright
      if: ${{ inputs.install-playwright == 'true' }}
      uses: ./.github/actions/setup-playwright
      with:
        browsers: ${{ inputs.playwright-browsers }}
